/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface KernelStorageInterface extends utils.Interface {
  functions: {
    "apps(bytes32,bytes32)": FunctionFragment;
    "recoveryVaultAppId()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "apps" | "recoveryVaultAppId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "apps",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoveryVaultAppId",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "apps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoveryVaultAppId",
    data: BytesLike
  ): Result;

  events: {};
}

export interface KernelStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: KernelStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    apps(
      arg0: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    recoveryVaultAppId(overrides?: CallOverrides): Promise<[string]>;
  };

  apps(
    arg0: BytesLike,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  recoveryVaultAppId(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    apps(
      arg0: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    recoveryVaultAppId(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    apps(
      arg0: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recoveryVaultAppId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    apps(
      arg0: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recoveryVaultAppId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
