/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  BaseTemplate,
  BaseTemplateInterface,
} from "../../../../@aragon/templates-shared/contracts/BaseTemplate";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";

const _abi = [
  {
    inputs: [
      {
        name: "_daoFactory",
        type: "address",
      },
      {
        name: "_ens",
        type: "address",
      },
      {
        name: "_miniMeFactory",
        type: "address",
      },
      {
        name: "_aragonID",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "dao",
        type: "address",
      },
    ],
    name: "DeployDao",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "dao",
        type: "address",
      },
    ],
    name: "SetupDao",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "token",
        type: "address",
      },
    ],
    name: "DeployToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "appProxy",
        type: "address",
      },
      {
        indexed: false,
        name: "appId",
        type: "bytes32",
      },
    ],
    name: "InstalledApp",
    type: "event",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516080806103e0833981018060405281019080805190602001909291908051906020019092919080519060200190929190805190602001909291905050506100698361034b640100000000026401000000009004565b6040805190810160405280601981526020017f54454d504c4154455f454e535f4e4f545f434f4e545241435400000000000000815250901515610147576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825283818151815260200191508051906020019080838360005b8381101561010c5780820151818401526020810190506100f1565b50505050905090810190601f1680156101395780820380516001836020036101000a031916815260200191505b509250505060405180910390fd5b506101608461034b640100000000026401000000009004565b6040805190810160405280601d81526020017f54454d504c4154455f44414f5f4641435f4e4f545f434f4e545241435400000081525090151561023e576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825283818151815260200191508051906020019080838360005b838110156102035780820151818401526020810190506101e8565b50505050905090810190601f1680156102305780820380516001836020036101000a031916815260200191505b509250505060405180910390fd5b50826000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555080600360006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555083600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555081600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505050505061039d565b600080600073ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff16141561038c5760009150610397565b823b90506000811191505b50919050565b6035806103ab6000396000f3006080604052600080fd00a165627a7a72305820b7d2e8167aaecaeeb317867f74195d3a271e10ee5cbc655a4c7ec56b221d90cc0029";

type BaseTemplateConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BaseTemplateConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BaseTemplate__factory extends ContractFactory {
  constructor(...args: BaseTemplateConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _daoFactory: string,
    _ens: string,
    _miniMeFactory: string,
    _aragonID: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BaseTemplate> {
    return super.deploy(
      _daoFactory,
      _ens,
      _miniMeFactory,
      _aragonID,
      overrides || {}
    ) as Promise<BaseTemplate>;
  }
  override getDeployTransaction(
    _daoFactory: string,
    _ens: string,
    _miniMeFactory: string,
    _aragonID: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _daoFactory,
      _ens,
      _miniMeFactory,
      _aragonID,
      overrides || {}
    );
  }
  override attach(address: string): BaseTemplate {
    return super.attach(address) as BaseTemplate;
  }
  override connect(signer: Signer): BaseTemplate__factory {
    return super.connect(signer) as BaseTemplate__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BaseTemplateInterface {
    return new utils.Interface(_abi) as BaseTemplateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BaseTemplate {
    return new Contract(address, _abi, signerOrProvider) as BaseTemplate;
  }
}
