/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Autopetrified } from "./Autopetrified";
export type { DelegateProxy } from "./DelegateProxy";
export type { DepositableDelegateProxy } from "./DepositableDelegateProxy";
export type { DepositableStorage } from "./DepositableStorage";
export type { IForwarder } from "./IForwarder";
export type { IVaultRecoverable } from "./IVaultRecoverable";
export type { Initializable } from "./Initializable";
export type { Petrifiable } from "./Petrifiable";
export type { VaultRecoverable } from "./VaultRecoverable";
