/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IACLOracle,
  IACLOracleInterface,
} from "../../../../../@aragon/os/contracts/acl/IACLOracle";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "who",
        type: "address",
      },
      {
        name: "where",
        type: "address",
      },
      {
        name: "what",
        type: "bytes32",
      },
      {
        name: "how",
        type: "uint256[]",
      },
    ],
    name: "canPerform",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class IACLOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IACLOracleInterface {
    return new utils.Interface(_abi) as IACLOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IACLOracle {
    return new Contract(address, _abi, signerOrProvider) as IACLOracle;
  }
}
