/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ens from "./ens";
export { IFIFSResolvingRegistrar__factory } from "./IFIFSResolvingRegistrar__factory";
