/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iKernelSol from "./IKernel.sol";
export { Kernel__factory } from "./Kernel__factory";
export { KernelProxy__factory } from "./KernelProxy__factory";
export { KernelStorage__factory } from "./KernelStorage__factory";
