/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc1271Sol from "./ERC1271.sol";
export { IERC165__factory } from "./IERC165__factory";
export { IERC721Receiver__factory } from "./IERC721Receiver__factory";
