/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AppProxyBase } from "./AppProxyBase";
export type { AppProxyPinned } from "./AppProxyPinned";
export type { AppProxyUpgradeable } from "./AppProxyUpgradeable";
export type { AppStorage } from "./AppStorage";
export type { AragonApp } from "./AragonApp";
