/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface IEVMScriptExecutorInterface extends utils.Interface {
  functions: {
    "execScript(bytes,bytes,address[])": FunctionFragment;
    "executorType()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "execScript" | "executorType"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execScript",
    values: [BytesLike, BytesLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executorType",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "execScript", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executorType",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IEVMScriptExecutor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IEVMScriptExecutorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    execScript(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executorType(overrides?: CallOverrides): Promise<[string]>;
  };

  execScript(
    script: BytesLike,
    input: BytesLike,
    blacklist: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executorType(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    execScript(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: CallOverrides
    ): Promise<string>;

    executorType(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    execScript(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executorType(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    execScript(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executorType(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
