/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as appsAgent from "./apps-agent";
import type * as appsFinance from "./apps-finance";
import type * as appsPayroll from "./apps-payroll";
import type * as appsSharedMinime from "./apps-shared-minime";
import type * as appsSurvey from "./apps-survey";
import type * as appsTokenManager from "./apps-token-manager";
import type * as appsVault from "./apps-vault";
import type * as appsVoting from "./apps-voting";
import type * as id from "./id";
import type * as os from "./os";
import type * as ppfContracts from "./ppf-contracts";
import type * as templatesShared from "./templates-shared";

export type { appsAgent };

export type { appsFinance };

export type { appsPayroll };

export type { appsSharedMinime };

export type { appsSurvey };

export type { appsTokenManager };

export type { appsVault };

export type { appsVoting };

export type { id };

export type { os };

export type { ppfContracts };

export type { templatesShared };
