/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Tanda__factory } from "./Tanda__factory";
export { TandaLend__factory } from "./TandaLend__factory";
