/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKernel__factory } from "./IKernel__factory";
export { IKernelEvents__factory } from "./IKernelEvents__factory";
