/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface MembershipTemplateInterface extends utils.Interface {
  functions: {
    "newToken(string,string)": FunctionFragment;
    "newInstance(string,address[],uint64[3],uint64,bool,uint256[4])": FunctionFragment;
    "newInstance(string,address[],uint64[3],uint64,bool)": FunctionFragment;
    "newTokenAndInstance(string,string,string,address[],uint64[3],uint64,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "newToken"
      | "newInstance(string,address[],uint64[3],uint64,bool,uint256[4])"
      | "newInstance(string,address[],uint64[3],uint64,bool)"
      | "newTokenAndInstance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "newToken",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "newInstance(string,address[],uint64[3],uint64,bool,uint256[4])",
    values: [
      string,
      string[],
      [BigNumberish, BigNumberish, BigNumberish],
      BigNumberish,
      boolean,
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "newInstance(string,address[],uint64[3],uint64,bool)",
    values: [
      string,
      string[],
      [BigNumberish, BigNumberish, BigNumberish],
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "newTokenAndInstance",
    values: [
      string,
      string,
      string,
      string[],
      [BigNumberish, BigNumberish, BigNumberish],
      BigNumberish,
      boolean
    ]
  ): string;

  decodeFunctionResult(functionFragment: "newToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "newInstance(string,address[],uint64[3],uint64,bool,uint256[4])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newInstance(string,address[],uint64[3],uint64,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newTokenAndInstance",
    data: BytesLike
  ): Result;

  events: {
    "DeployDao(address)": EventFragment;
    "SetupDao(address)": EventFragment;
    "DeployToken(address)": EventFragment;
    "InstalledApp(address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeployDao"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetupDao"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeployToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InstalledApp"): EventFragment;
}

export interface DeployDaoEventObject {
  dao: string;
}
export type DeployDaoEvent = TypedEvent<[string], DeployDaoEventObject>;

export type DeployDaoEventFilter = TypedEventFilter<DeployDaoEvent>;

export interface SetupDaoEventObject {
  dao: string;
}
export type SetupDaoEvent = TypedEvent<[string], SetupDaoEventObject>;

export type SetupDaoEventFilter = TypedEventFilter<SetupDaoEvent>;

export interface DeployTokenEventObject {
  token: string;
}
export type DeployTokenEvent = TypedEvent<[string], DeployTokenEventObject>;

export type DeployTokenEventFilter = TypedEventFilter<DeployTokenEvent>;

export interface InstalledAppEventObject {
  appProxy: string;
  appId: string;
}
export type InstalledAppEvent = TypedEvent<
  [string, string],
  InstalledAppEventObject
>;

export type InstalledAppEventFilter = TypedEventFilter<InstalledAppEvent>;

export interface MembershipTemplate extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MembershipTemplateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    newToken(
      _name: string,
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "newInstance(string,address[],uint64[3],uint64,bool,uint256[4])"(
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      _payrollSettings: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "newInstance(string,address[],uint64[3],uint64,bool)"(
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newTokenAndInstance(
      _tokenName: string,
      _tokenSymbol: string,
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  newToken(
    _name: string,
    _symbol: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "newInstance(string,address[],uint64[3],uint64,bool,uint256[4])"(
    _id: string,
    _members: string[],
    _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
    _financePeriod: BigNumberish,
    _useAgentAsVault: boolean,
    _payrollSettings: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "newInstance(string,address[],uint64[3],uint64,bool)"(
    _id: string,
    _members: string[],
    _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
    _financePeriod: BigNumberish,
    _useAgentAsVault: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newTokenAndInstance(
    _tokenName: string,
    _tokenSymbol: string,
    _id: string,
    _members: string[],
    _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
    _financePeriod: BigNumberish,
    _useAgentAsVault: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    newToken(
      _name: string,
      _symbol: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "newInstance(string,address[],uint64[3],uint64,bool,uint256[4])"(
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      _payrollSettings: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<void>;

    "newInstance(string,address[],uint64[3],uint64,bool)"(
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      overrides?: CallOverrides
    ): Promise<[string, string, string]>;

    newTokenAndInstance(
      _tokenName: string,
      _tokenSymbol: string,
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "DeployDao(address)"(dao?: null): DeployDaoEventFilter;
    DeployDao(dao?: null): DeployDaoEventFilter;

    "SetupDao(address)"(dao?: null): SetupDaoEventFilter;
    SetupDao(dao?: null): SetupDaoEventFilter;

    "DeployToken(address)"(token?: null): DeployTokenEventFilter;
    DeployToken(token?: null): DeployTokenEventFilter;

    "InstalledApp(address,bytes32)"(
      appProxy?: null,
      appId?: null
    ): InstalledAppEventFilter;
    InstalledApp(appProxy?: null, appId?: null): InstalledAppEventFilter;
  };

  estimateGas: {
    newToken(
      _name: string,
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "newInstance(string,address[],uint64[3],uint64,bool,uint256[4])"(
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      _payrollSettings: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "newInstance(string,address[],uint64[3],uint64,bool)"(
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newTokenAndInstance(
      _tokenName: string,
      _tokenSymbol: string,
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    newToken(
      _name: string,
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "newInstance(string,address[],uint64[3],uint64,bool,uint256[4])"(
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      _payrollSettings: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "newInstance(string,address[],uint64[3],uint64,bool)"(
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newTokenAndInstance(
      _tokenName: string,
      _tokenSymbol: string,
      _id: string,
      _members: string[],
      _votingSettings: [BigNumberish, BigNumberish, BigNumberish],
      _financePeriod: BigNumberish,
      _useAgentAsVault: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
