/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface DepositableDelegateProxyInterface extends utils.Interface {
  functions: {
    "proxyType()": FunctionFragment;
    "isDepositable()": FunctionFragment;
    "implementation()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "proxyType" | "isDepositable" | "implementation"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "proxyType", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isDepositable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "proxyType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDepositable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;

  events: {
    "ProxyDeposit(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProxyDeposit"): EventFragment;
}

export interface ProxyDepositEventObject {
  sender: string;
  value: BigNumber;
}
export type ProxyDepositEvent = TypedEvent<
  [string, BigNumber],
  ProxyDepositEventObject
>;

export type ProxyDepositEventFilter = TypedEventFilter<ProxyDepositEvent>;

export interface DepositableDelegateProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DepositableDelegateProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    proxyType(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { proxyTypeId: BigNumber }>;

    isDepositable(overrides?: CallOverrides): Promise<[boolean]>;

    implementation(
      overrides?: CallOverrides
    ): Promise<[string] & { codeAddr: string }>;
  };

  proxyType(overrides?: CallOverrides): Promise<BigNumber>;

  isDepositable(overrides?: CallOverrides): Promise<boolean>;

  implementation(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    proxyType(overrides?: CallOverrides): Promise<BigNumber>;

    isDepositable(overrides?: CallOverrides): Promise<boolean>;

    implementation(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ProxyDeposit(address,uint256)"(
      sender?: null,
      value?: null
    ): ProxyDepositEventFilter;
    ProxyDeposit(sender?: null, value?: null): ProxyDepositEventFilter;
  };

  estimateGas: {
    proxyType(overrides?: CallOverrides): Promise<BigNumber>;

    isDepositable(overrides?: CallOverrides): Promise<BigNumber>;

    implementation(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    proxyType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isDepositable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    implementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
