/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as iKernelSol from "./IKernel.sol";

export type { iKernelSol };
export type { Kernel } from "./Kernel";
export type { KernelProxy } from "./KernelProxy";
export type { KernelStorage } from "./KernelStorage";
