/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as ens from "./ens";

export type { ens };
export type { IFIFSResolvingRegistrar } from "./IFIFSResolvingRegistrar";
