/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IFIFSResolvingRegistrar,
  IFIFSResolvingRegistrarInterface,
} from "../../../../@aragon/id/contracts/IFIFSResolvingRegistrar";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_subnode",
        type: "bytes32",
      },
      {
        name: "_owner",
        type: "address",
      },
    ],
    name: "register",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_subnode",
        type: "bytes32",
      },
      {
        name: "_owner",
        type: "address",
      },
      {
        name: "_resolver",
        type: "address",
      },
    ],
    name: "registerWithResolver",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFIFSResolvingRegistrar__factory {
  static readonly abi = _abi;
  static createInterface(): IFIFSResolvingRegistrarInterface {
    return new utils.Interface(_abi) as IFIFSResolvingRegistrarInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFIFSResolvingRegistrar {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IFIFSResolvingRegistrar;
  }
}
