/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as miniMeTokenSol from "./MiniMeToken.sol";
export { ITokenController__factory } from "./ITokenController__factory";
